import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastProvider } from '../app/component/toastContext';

import ReactQuery from './component/ReactQuery';
import { Session } from 'next-auth';
import NextAuthProvider from './component/NextAuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, session }: { 
  children: React.ReactNode; 
  session: Session | null | undefined; 
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`bg-white text-black px-5 ${inter.className}`}>
        <NextAuthProvider session={session}>
          <ToastProvider>
            <ReactQuery>
              {children}
            </ReactQuery>
          </ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
